name: get_ev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.1
  provider: ^5.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6

  flutter:
    sdk: flutter
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
